// app/layout.tsx or app/(main)/layout.tsx
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { verifyRefreshJwt } from "./backend/jwt/verifyjwt";
import Provider from "./context/Providers";
import "./styles/animations.css";
import "./styles/components.css";
import "./styles/globals.css";
import { User } from "./types/user";
import Script from "next/script";

export const metadata: Metadata = {
  title: "AureusNova",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const token = cookieStore.get("refreshToken")?.value;
  let user: User | null = null;

  if (token) {
    const decoded = verifyRefreshJwt(token) as User | null;
    if (decoded) user = decoded;
  }

  return (
    <html lang="en">
      <body>
        <Provider serverUser={user}>{children}</Provider>
        <Script
          id="smartsupp-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var _smartsupp = _smartsupp || {};
              _smartsupp.key = '2d763a84b71acbe161e4fbfc5a8af11bb399baf9';
              window.smartsupp||(function(d) {
                var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
                s=d.getElementsByTagName('script')[0];c=d.createElement('script');
                c.type='text/javascript';c.charset='utf-8';c.async=true;
                c.src='https://www.smartsuppchat.com/loader.js?';
                s.parentNode.insertBefore(c,s);
              })(document);
            `,
          }}
        />
      </body>
    </html>
  );
}
