// app/layout.tsx or app/(main)/layout.tsx
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { verifyJwt } from "./backend/jwt/verifyjwt";
import ContextProvider from "./context";
import Provider from "./context/Providers";
import "./styles/animations.css";
import "./styles/components.css";
import "./styles/globals.css";
import { User } from "./types/user";

export const metadata: Metadata = {
  title: "AureusNova",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  let user: User | null = null;

  if (token) {
    const decoded = verifyJwt(token) as User | null;
    if (decoded) user = decoded;
  }

  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <Provider serverUser={user}>{children}</Provider>
        </ContextProvider>
      </body>
    </html>
  );
}
